### ISSUE TITLE
Raw data access

### ISSUE THREAD

**Issue by cramirezs** [NUPulmonary/2020_Grant#1]
Dear Authors,

Could you please help me understand your data? I am trying to access the raw UMI counts in the anndata file, but I am unable to find them. I believe I only see the normalized/log normalized, and scaled matrices.

Kind Regards,
Ciro

**Comment by cramirezs** [comment]
I exp(X) - 1 the normalized data, but I thought you should know. Thank you!

**Comment by mxposed** [comment]
In the anndata objects [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE155249) `adata.raw.X` is `log(X + 1)` log-scaled gene expression of _normalized_ counts to 10000 UMIs per cell.

`adata.X` is z-scored version of `adata.raw.X`

The raw UMI counts (not normalized to same depth per cell) are not included in the anndata object, sorry. The can be found individually for each sample on GEO in cellranger h5 format, for instance [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4698176)

**Comment by vijaybioinfo** [comment]
Thank you for your quick response! I am using the data after transforming: exp(X) - 1.

**Comment by cramirezs** [comment]
Thank you for your quick response! I am using the data after transforming: exp(adata.raw.X) - 1.

**Comment by mxposed** [comment]
In that case that is not the raw UMI counts, but the raw UMI counts normalized to 10000 UMIs per cell (within sample)

**Comment by mxposed** [comment]
Feel free to reopen
